name: tifli
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase - all compatible versions
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.6.0
  firebase_messaging: ^15.2.10
  firebase_analytics: ^11.6.0
  
  # Flutter & UI
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  fl_chart: ^1.1.1
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.2.1
  flutter_bloc: ^9.1.1
  equatable: ^2.0.5
  
  # Supabase
  supabase_flutter: ^2.12.0
  
  # Utilities
  image_picker: ^1.0.5
  path: ^1.8.3
  shared_preferences: ^2.5.3
  cached_network_image: ^3.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  material_symbols_icons: ^4.0.0
  font_awesome_flutter: ^10.7.0
  flutter_lints: ^6.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/icons/feeding-bottle.svg
    - assets/images/
  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
    - family: Afacad
      fonts:
        - asset: assets/fonts/Afacad-Regular.ttf
        - asset: assets/fonts/Afacad-SemiBold.ttf
          weight: 600